// AUTH
export const SET_AUTH = 'SET_AUTH'

// USERS
export const GET_USER_PROFILE = 'GET_USER_PROFILE'

// GOALS
export const GET_USER_GOALS = 'GET_USER_GOALS'
export const ADD_USER_GOALS = 'ADD_USER_GOALS'
export const UPDATE_USER_GOALS = 'UPDATE_USER_GOALS'
export const DELETE_USER_GOALS = 'DELETE_USER_GOALS'

// EXPENSE
export const GET_USER_EXPENSES = 'GET_USER_EXPENSE'
export const SELECT_USER_EXPENSE = 'SELECT_USER_EXPENSE'
export const ADD_USER_EXPENSE = 'ADD_USER_EXPENSE'
export const UPDATE_USER_EXPENSE = 'UPDATE_USER_EXPENSE'
export const DELETE_USER_EXPENSE = 'DELETE_USER_EXPENSE'
export const CLEAR_USER_EXPENSE = 'CLEAR_USER_EXPENSE'

// INCOME
export const GET_USER_INCOME = 'GET_USER_INCOME'
export const SELECT_USER_INCOME = 'SELECT_USER_INCOME'
export const ADD_USER_INCOME = 'ADD_USER_INCOME'
export const UPDATE_USER_INCOME = 'UPDATE_USER_INCOME'
export const DELETE_USER_INCOME = 'DELETE_USER_INCOME'
export const CLEAR_USER_INCOME = 'CLEAR_USER_INCOME'

// MODAL
export const SET_MODAL_AUTH_FORM = 'SET_MODAL_AUTH_FORM'
export const SET_MODAL_AUTH_OPEN = 'SET_MODAL_AUTH_OPEN'
export const SET_MODAL_EXPENSE_FORM = 'SET_MODAL_EXPENSE_FORM'
export const SET_MODAL_EXPENSE_OPEN = 'SET_MODAL_EXPENSE_OPEN'
export const SET_MODAL_INCOME_FORM = 'SET_MODAL_INCOME_FORM'
export const SET_MODAL_INCOME_OPEN = 'SET_MODAL_INCOME_OPEN'
